---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk

inputs:
- name: spring-session-data-couchbase-github

outputs:
- name: spring-session-data-couchbase-artifactory

caches:
- path: maven

run:
  path: spring-session-data-couchbase-github/ci/build.sh
